name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Build and run Docker image
        run: |
          docker build -t my-python-app ./tests
          docker run --rm my-python-app