name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker and run tests
        run: |
          docker run --rm -v $PWD:/workdir -w /workdir lukechilds/dockerpi:latest /bin/bash -c " \
            apt-get update && \
            apt-get install -y python3-pip && \
            pip3 install --upgrade pip && \
            pip3 install -r ./tests/requirements.txt && \
            python3 -m pytest -vvs tests.py
          "
