name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Set up Docker for Raspberry Pi emulation and run tests
        run: |
          docker run --rm -v $PWD:/workdir -w /workdir lukechilds/dockerpi:latest bash -c "apt-get update && apt-get install -y python3-pip && pip3 install -r ./tests/requirements.txt && pytest -vvs tests.py"
          